theme = "zed_onedark"

[editor]
line-number = "absolute"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[keys.insert]
"," = { "," = "normal_mode" } # Maps `,,` to exit insert mode
