[[language]]
name = "python"
roots = ["pyproject.toml", "."]
language-servers = ["pyright"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = false

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
